// Notification
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const FADE_MESSAGE = 'FADE_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SHOW_TOAST = 'SHOW_TOAST';

// Check credentials
export const CHECK_CREDS = 'CHECK_CREDS';
// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const LOGIN_REQUIRED = 'LOGIN_REQUIRED';
// Log out
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Products - CRUD Requests
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const READ_PRODUCT_REQUEST = 'READ_PRODUCT_REQUEST';
export const READ_PRODUCTS_REQUEST = 'READ_PRODUCTS_REQUEST';
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';

// Products - Responses
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCT_REQUEST_SUCCESS';
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const PRODUCT_REQUEST_FAILURE = 'PRODUCT_REQUEST_FAILURE';

// Products - Editing
export const MANAGE_EDIT = 'MANAGE_EDIT';

// Cart actions
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INIT_CART = 'INIT_CART';
export const FILL_CART = 'FILL_CART';
export const GET_CART_PRODUCTS_SUCCESS = 'GET_CART_PRODUCTS_SUCCESS';
export const GET_CART_PRODUCTS_FAILURE = 'GET_CART_PRODUCTS_FAILURE';
export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';